import os
import json
import chevron

from .tiny_factory import TinyFactory
from tinytroupe.factory import logger
from tinytroupe import openai_utils
from tinytroupe.agent import TinyPerson
import tinytroupe.utils as utils
from tinytroupe.control import transactional

class TinyPersonFactory(TinyFactory):
    """
    Facilitates the creation of :class:`~tinytroupe.agent.tiny_person.TinyPerson` instances
    using a Language Model (LLM) to generate persona specifications.

    The factory is initialized with a `context_text` that provides a general theme or setting.
    When generating agents, more specific `agent_particularities` can be provided to further
    guide the LLM. The factory attempts to produce diverse agents by keeping track of
    generated names and mini-biographies to avoid exact duplicates.

    **Core Functionality:**

    *   Generates individual :class:`~tinytroupe.agent.tiny_person.TinyPerson` objects with LLM-defined personas.
    *   Can generate batches of agents based on shared or individual particularities.
    *   Uses LLM parameters like temperature, frequency penalty, and presence penalty to control
        the creativity and style of generated personas.
    *   Includes a static method to generate multiple `TinyPersonFactory` instances, each
        specialized for a sub-context derived from a more generic theme.

    :param context_text: The broader thematic context that guides all persona generation
                         from this factory (e.g., "A bustling medieval marketplace",
                         "Survivors on a desert island").
    :type context_text: str
    :param simulation_id: An optional identifier for the simulation this factory is part of.
                          This is not directly used in persona generation but can be useful for organizing
                          larger simulation experiments. Defaults to None.
    :type simulation_id: str, optional

    **Attributes:**

    *   ``context_text (str)``: The guiding context for persona generation.
    *   ``generated_minibios (list)``: Stores mini-biographies of agents generated by this instance
                                     to encourage diversity in subsequent generations.
    *   ``generated_names (list)``: Stores names of agents generated by this instance to help
                                  avoid direct name collisions during generation by this factory.
                                  Note: Global name uniqueness is checked against `TinyPerson.all_agents_names()`.

    **Basic Usage Example:**
    **Basic Usage Example:**

    .. code-block:: python

        from tinytroupe.factory import TinyPersonFactory

        # 1. Create a factory with a specific context
        context = "A team of explorers stranded on a mysterious, uncharted island in the Pacific."
        explorer_factory = TinyPersonFactory(context_text=context)

        # 2. Generate a specific type of person within that context
        navigator_particulars = "The ship's navigator, highly skilled but haunted by a past mistake."
        navigator = explorer_factory.generate_person(
            agent_particularities=navigator_particulars,
            temperature=1.6 # Encourage more creative/unique details
        )

        if navigator:
            print(f"Generated: {navigator.name}")
            print(f"Occupation: {navigator.get('occupation').get('title', 'N/A')}")
            print(f"Minibio snippet: {navigator.minibio()[:100]}...")
            # Example (output will vary):
            # Generated: Captain Eva Rostova
            # Occupation: Navigator
            # Minibio snippet: Captain Eva Rostova is a 38 year old Navigator, Russian, currently living in Unknown. Haunted by t...

        # 3. Generate a batch of people with a general particularity
        crew_members = explorer_factory.generate_people(
            number_of_people=2,
            agent_particularities="General crew members, trying to survive.",
            temperature=1.4
        )
        print(f"\nGenerated {len(crew_members)} crew members:")
        for member in crew_members:
            print(f"- {member.name}, a {member.get('occupation').get('title', 'crew member')}")
            # Example (output will vary):
            # Generated 2 crew members:
            # - Jax 'Fixit' Riley, a Mechanic
            # - Dr. Lena Hanson, a Botanist
    """

    def __init__(self, context_text: str, simulation_id: str = None):
        """
        Initializes a TinyPersonFactory instance.

        :param context_text: The context text that will guide the generation of
                             :class:`~tinytroupe.agent.tiny_person.TinyPerson` instances.
                             This could be a description of a scenario, a setting, or a general theme.
        :type context_text: str
        :param simulation_id: An optional identifier for the simulation this factory is part of.
        :type simulation_id: str, optional
        """
        super().__init__(simulation_id)
        self.person_prompt_template_path = os.path.join(os.path.dirname(__file__), 'prompts/generate_person.mustache')
        self.context_text = context_text
        self.generated_minibios = [] # keep track of the generated persons. We keep the minibio to avoid generating the same person twice.
        self.generated_names = []

    @staticmethod
    def generate_person_factories(number_of_factories, generic_context_text):
        """
        Generates multiple `TinyPersonFactory` instances, each with a more specific
        context derived by an LLM from a generic `generic_context_text`.

        This is useful for creating a set of diverse factories that can then generate
        agents for different, but related, sub-contexts within a larger simulation theme.
        For example, a generic context of "a fantasy kingdom" could yield factories for
        "the royal court," "a remote wizard's tower," and "a bustling port city."

        :param number_of_factories: The desired number of `TinyPersonFactory` instances.
        :type number_of_factories: int
        :param generic_context_text: A broad context description that the LLM will use
                                     as a basis to generate more specific contexts for each factory.
        :type generic_context_text: str
        :return: A list of newly created `TinyPersonFactory` instances, or None if LLM-based
                 context generation fails.
        :rtype: list, optional
        """

        logger.info(f"Starting the generation of the {number_of_factories} person factories based on that context: {generic_context_text}")

        system_prompt = open(os.path.join(os.path.dirname(__file__), 'prompts/generate_person_factory.md')).read()

        messages = []
        messages.append({"role": "system", "content": system_prompt})

        user_prompt = chevron.render("Please, create {{number_of_factories}} person descriptions based on the following broad context: {{context}}", {
            "number_of_factories": number_of_factories,
            "context": generic_context_text
        })

        messages.append({"role": "user", "content": user_prompt})

        response = openai_utils.client().send_message(messages)

        if response is not None:
            result = utils.extract_json(response["content"])

            factories = []
            for i in range(number_of_factories):
                logger.debug(f"Generating person factory with description: {result[i]}")
                factories.append(TinyPersonFactory(result[i]))

            return factories

        return None

    def generate_person(self, 
                        agent_particularities:str=None, 
                        temperature:float=1.5, 
                        frequency_penalty:float=0.0,
                        presence_penalty:float=0.0, 
                        attepmpts:int=10):
        """
        Generates a single :class:`~tinytroupe.agent.tiny_person.TinyPerson` instance using an LLM.

        The persona generation is guided by the factory's `context_text` and can be
        further refined by the `agent_particularities` argument. The method attempts to
        generate a unique agent by checking against previously generated names within this
        factory and globally via `TinyPerson.all_agents_names()`. It also uses previously
        generated mini-biographies from this factory in the prompt to encourage diversity.

        LLM Generation Parameters:
        *   `temperature`: Controls randomness. Higher values (e.g., 1.0-2.0) yield more creative but
            potentially less coherent results. Lower values (e.g., 0.2-0.7) make output more focused.
        *   `frequency_penalty`: Positive values penalize new tokens based on their existing
            frequency in the text so far, reducing repetition of the same lines or phrases.
        *   `presence_penalty`: Positive values penalize new tokens based on whether they have
            appeared in the text so far, encouraging the model to introduce new concepts.

        :param agent_particularities: Specific details or characteristics to guide the
                                      generation of this particular agent (e.g., "The cynical detective",
                                      "An optimistic young inventor"). Defaults to None.
        :type agent_particularities: str, optional
        :param temperature: LLM temperature setting. Defaults to 1.5.
        :type temperature: float, optional
        :param frequency_penalty: LLM frequency penalty. Defaults to 0.0.
        :type frequency_penalty: float, optional
        :param presence_penalty: LLM presence penalty. Defaults to 0.0.
        :type presence_penalty: float, optional
        :param attepmpts: Number of attempts to generate a unique and valid agent if initial
                          attempts fail (e.g., due to name collision or parsing errors). Defaults to 10.
        :type attepmpts: int, optional
        :return: A newly created `TinyPerson` instance if generation is successful and the
                 agent name is unique, otherwise None.
        :rtype: TinyPerson, optional
        """

        logger.info(f"Starting the person generation based on that context: {self.context_text}")


        # read example specs from files.
        # These examples help the LLM understand the desired JSON output structure for the persona.
        example_1 = json.load(open(os.path.join(os.path.dirname(__file__), '../examples/agents/Friedrich_Wolf.agent.json')))
        example_2 = json.load(open(os.path.join(os.path.dirname(__file__), '../examples/agents/Sophie_Lefevre.agent.json')))

        # We must include all agent names generated in the whole of the simulation, not only the ones generated by this factory,
        # since they all share the same name space.
        #
        # For the minibios, we only need to keep track of the ones generated by this factory, since they are unique to each factory
        # and are used to guide the sampling process.
        prompt = chevron.render(open(self.person_prompt_template_path).read(), {
            "context": self.context_text,
            "agent_particularities": agent_particularities,
            
            #Note that we need to dump them to JSON strings, to ensure we get double quotes,
            # and other formatting issues are avoided.
            "example_1": json.dumps(example_1["persona"], indent=4),
            "example_2": json.dumps(example_2["persona"], indent=4),

            "already_generated_minibios": self.generated_minibios,
            "already_generated_names": TinyPerson.all_agents_names()
        })

        def aux_generate(attempt):

            messages = []
            messages += [{"role": "system", "content": "You are a system that generates specifications for realistic simulations of people. You follow the generation rules and constraints carefully."},
                        {"role": "user", "content": prompt}]
            
            if attempt > 1:
                # we failed once already due to repetition, so we try to further reinforce the message to avoid repetition.
                messages.append({"role": "user", "content": "IMPORTANT: Please ensure you **do not** generate the same name again. Agent names **must** be unique."+ \
                                                            "Read the list of already generated names to avoid repetition. If necessary, generate a longer name to ensure it is new."})

            # due to a technicality, we need to call an auxiliary method to be able to use the transactional decorator.
            message = self._aux_model_call(messages=messages, 
                                            temperature=temperature,
                                            frequency_penalty=frequency_penalty,
                                            presence_penalty=presence_penalty)

            if message is not None:
                result = utils.extract_json(message["content"])

                logger.debug(f"At attempt {attempt}, generated person parameters:\n{json.dumps(result, indent=4, sort_keys=True)}")

                # only accept the generated spec if the name is not already in the generated names, because they must be unique.
                if result["name"].lower() not in self.generated_names:
                    return result
                else:
                    logger.info(f"Person with name {result['name']} was already generated, cannot be reused.")

            return None # no suitable agent was generated
        
        agent_spec = None
        attempt = 0
        while agent_spec is None and attempt < attepmpts:
            try:
                attempt += 1
                agent_spec = aux_generate(attempt=attempt)
            except Exception as e:
                logger.error(f"Error while generating agent specification: {e}")
        
        # create the fresh agent
        if agent_spec is not None:
            # the agent is created here. This is why the present method cannot be cached. Instead, an auxiliary method is used
            # for the actual model call, so that it gets cached properly without skipping the agent creation.
            person = TinyPerson(agent_spec["name"])
            self._setup_agent(person, agent_spec)
            self.generated_minibios.append(person.minibio())
            self.generated_names.append(person.get("name").lower())
            return person
        else:
            logger.error(f"Could not generate an agent after {attepmpts} attempts.")
            return None

    def generate_people(self, number_of_people:int, 
                        agent_particularities:str=None, 
                        temperature:float=1.5, 
                        frequency_penalty:float=0.0,
                        presence_penalty:float=0.0,
                        attepmpts:int=10, 
                        verbose:bool=False) -> list:
        """
        Generates a list of :class:`~tinytroupe.agent.tiny_person.TinyPerson` instances.

        This method repeatedly calls :meth:`~generate_person` to create the specified
        number of agents. The same `agent_particularities` (if provided) and LLM parameters
        are used for each generation attempt within this batch.

        :param number_of_people: The number of `TinyPerson` instances to generate.
        :type number_of_people: int
        :param agent_particularities: Specific details or characteristics to guide the
                                      generation of these agents. This can be a general description
                                      that applies to the group (e.g., "Villagers from Oakhaven").
                                      Defaults to None.
        :type agent_particularities: str, optional
        :param temperature: LLM temperature setting. Defaults to 1.5.
        :type temperature: float, optional
        :param frequency_penalty: LLM frequency penalty. Defaults to 0.0.
        :type frequency_penalty: float, optional
        :param presence_penalty: LLM presence penalty. Defaults to 0.0.
        :type presence_penalty: float, optional
        :param attepmpts: Number of generation attempts per person. Defaults to 10.
        :type attepmpts: int, optional
        :param verbose: If True, prints information (minibio) about each successfully
                        generated person to the console. Defaults to False.
        :type verbose: bool, optional
        :return: A list of generated `TinyPerson` instances. If some generations fail,
                 the list may contain fewer than `number_of_people` agents.
        :rtype: list[TinyPerson]
        """
        people = []
        for i in range(number_of_people):
            person = self.generate_person(agent_particularities=agent_particularities, 
                                            temperature=temperature, 
                                            frequency_penalty=frequency_penalty,
                                            presence_penalty=presence_penalty,
                                            attepmpts=attepmpts)
            if person is not None:
                people.append(person)
                info_msg = f"Generated person {i+1}/{number_of_people}: {person.minibio()}"
                logger.info(info_msg)
                if verbose:
                    print(info_msg)
            else:
                logger.error(f"Could not generate person {i+1}/{number_of_people}.")

        return people
    
    @transactional
    def _aux_model_call(self, messages, temperature, frequency_penalty, presence_penalty):
        """
        Auxiliary method to make a model call. This is needed in order to be able to use the transactional decorator,
        due too a technicality - otherwise, the agent creation would be skipped during cache reutilization, and
        we don't want that.
        """
        return openai_utils.client().send_message(messages, 
                                                  temperature=temperature, 
                                                  frequency_penalty=frequency_penalty, 
                                                  presence_penalty=presence_penalty,
                                                  response_format={"type": "json_object"})
    
    @transactional
    def _setup_agent(self, agent, configuration):
        """
        Sets up the agent with the necessary elements.
        """
        agent.include_persona_definitions(configuration)
        
        # does not return anything, as we don't want to cache the agent object itself.
    
